altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  407e1565-ee6d-4a4f-b5af-35664f626133:
    cardView:
      - imageSize
      - filename
      - 'layoutElement:14b25d48-590b-4754-9fc3-573562547aad'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-11T23:17:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 68600dee-8f5f-4349-b58b-3a385ea2e626
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-01-12T00:28:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: true
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 14b25d48-590b-4754-9fc3-573562547aad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 83bc16ea-513d-4b70-9de8-57c734ecbff5
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: images
transformSubpath: ''
