columnSuffix: null
handle: homeIntro
instructions: null
name: 'Home intro'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 049a860c-378f-4b4b-8524-5f0b816892f7 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
